version: '3'
services:
  stellar-core-postgres:
    image: postgres:12
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=stellar-core
      - POSTGRES_PASSWORD=S0m3R4nd0mP455w0rd

  stellar-core:
    image: satoshipay/stellar-core:12.5.0
    restart: on-failure
    volumes:
      - core-data:/data
    environment:
      - DATABASE=postgresql://dbname=stellar-core user=postgres password=DATABASE_PASSWORD host=stellar-core-postgres
      - DATABASE_PASSWORD=S0m3R4nd0mP455w0rd
      - INITIALIZE_DB=false
      - INITIALIZE_HISTORY_ARCHIVES=false
      # public key GACVY6FX6ZSGBEWQF6DG25VOAB25F72EI4WS676QIO3HO2YBKAKDI44H
      - NODE_SEED=SDEZOI3BOCW6DUY23ZCJQALULOIEIQMZW4UTFXPRQEMMJMOG7CVD7WMO satoshipay-catchup
      - NODE_IS_VALIDATOR=true
      - NETWORK_PASSPHRASE=Test SDF Network ; September 2015
      - MAX_PEER_CONNECTIONS=30
      - "KNOWN_PEERS=\
        stellar-testnet-de-fra.satoshipay.io,\
        core-testnet1.stellar.org,\
        core-testnet2.stellar.org,\
        core-testnet3.stellar.org"
      - "PREFERRED_PEERS=\
        stellar-testnet-de-fra.satoshipay.io,\
        core-testnet1.stellar.org,\
        core-testnet2.stellar.org,\
        core-testnet3.stellar.org"
      - "NODE_NAMES=\
        GC5TQJOHBX6NRGJHKVN3YMQGCVHJHKND4J2CV6RYVPIYZRX7STPSLEJL satoshipay-testnet-de-fra,\
        GDKXE2OZMJIPOSLNA6N6F2BVCI3O777I2OOC4BV7VOYUEHYX7RTRYA7Y sdf1,\
        GCUCJTIYXSOXKBSNFGNFWW5MUQ54HKRPGJUTQFJ5RQXZXNOLNXYDHRAP sdf2,\
        GC2V2EFSXN6SQTWVYA5EPJPBWWIMSD2XQNKUOHGEKB535AQE2I6IXV2Z sdf3"
      - >-
          QUORUM_SET=[
            {
              "threshold_percent": 66,
              "validators": [
                "$$satoshipay-testnet-de-fra",
                "$$sdf1",
                "$$sdf2",
                "$$sdf3"
              ]
            }
          ]
      - KNOWN_CURSORS=HORIZON
      - UNSAFE_QUORUM=true
      - FAILURE_SAFETY=1
      - >-
          HISTORY={
            "satoshipay-testnet-de-fra": {"get": "curl -sf https://stellar-history-testnet-de-fra.satoshipay.io/{0} -o {1}"},
            "sdf1": {"get": "curl -sf http://history.stellar.org/prd/core-testnet/core_testnet_001/{0} -o {1}"},
            "sdf2": {"get": "curl -sf http://history.stellar.org/prd/core-testnet/core_testnet_002/{0} -o {1}"},
            "sdf3": {"get": "curl -sf http://history.stellar.org/prd/core-testnet/core_testnet_003/{0} -o {1}"},
            "local": {
              "get": "cp /data/history/{0} {1}",
              "put": "cp {0} /data/history/{1}",
              "mkdir": "mkdir -p /data/history/{0}"
            }
          }

volumes:
  db-data:
  core-data:
